#!/bin/csh -f

setenv CLAS_CALDB_RUNINDEX calib_user.RunIndexe1f

# environment for executables
setenv PATH /apps/gcc/4.8.0/bin:.:$PATH
setenv LD_LIBRARY_PATH /apps/gcc/4.8.0/lib64:$LD_LIBRARY_PATH
setenv CXX /apps/gcc/4.8.0/bin/c++
setenv CC  /apps/gcc/4.8.0/bin/gcc

# CLAS6 software - oh joy
setenv CLASPREFIX /u/home/clase1-6/clas6-trunk
setenv CLAS6INC ${CLASPREFIX}/build/include
setenv CLAS6LIB ${CLASPREFIX}/build/lib
setenv CLAS6BIN ${CLASPREFIX}/build/bin

#setenv ALIGNBITS 64
setenv ALIGNBITS 32
setenv PYTHONPATH ${CLASPREFIX}/lib/python:${PYTHONPATH}

# clas paths
setenv CLAS_PARMS /group/clas/parms
setenv LD_LIBRARY_PATH ${CLAS6LIB}:${LD_LIBRARY_PATH}

setenv PATH ${CLASPREFIX}/scripts:${CLAS6BIN}:${PATH}
set path = (/group/clas/tools/caldb $CLAS6BIN /apps/bin $path)

# perl scripts for clasdb
setenv PERL5LIB /group/clas/tools/caldb

# cernlib
#setenv CERNLIB /usr/lib64/cernlib/2006/lib
setenv CERNLIB /apps/cernlib/i386_rhel6/2005/lib/

# mysql
setenv MYSQLINC /usr/include/mysql
#setenv MYSQLLIB /usr/lib64/mysql
setenv MYSQLLIB /usr/lib/mysql

# tcl
setenv TCLLIB /usr/lib
