#!/bin/tcsh -f

# Setup the environment for GSIM and USER_ANA.
setenv CLAS_CALDB_RUNINDEX calib_user.RunIndexe1f
source /group/clas/builds/centos65/environment.csh 

# Get the utilities from my folders. 
set mainPath = "/u/home/dmriser/mydoc/cooking_supplies"

alias elast_gen      /u/home/dmriser/CLASSourceCode/elast_gen/elast_gen
alias elast_gen_cole /u/home/dmriser/CLASSourceCode/elast_gen_cole/elast_gen
alias dis_gen        /u/home/dmriser/CLASSourceCode/clasdis/clasdis
alias keppel_rad     /u/home/dmriser/CLASSourceCode/keppel_rad/keppel_rad
alias keppel_norad   /u/home/dmriser/CLASSourceCode/keppel_norad/keppel_norad
alias nt22maker      /u/home/dmriser/CLASSourceCode/nt22maker_dvcs/build/bin/nt22maker

# setup output based on input from command
set OUTDIR = $1
set GEN    = $2 
set PROJ   = $3 

# create outdir if it doesn't exist 
mkdir -p $OUTDIR/$PROJ

set JOBNUMBER = `getJobNumber $OUTDIR $PROJ`
echo " DOING JOB NUMBER $JOBNUMBER "
echo " "
mkdir -p $OUTDIR/$PROJ/JOB_$JOBNUMBER

# Begin processing the job.
echo " ------------ STARTING JOB ------------ "  > $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
echo " gen:       " `which $GEN`                >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
echo " GSIM:      " `which gsim_bat`            >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
echo " GPP:       " `which gpp_2008`            >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
echo " USER_ANA:  " `which user_ana`            >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
echo " nt22maker: " `which nt22maker`           >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
echo " ------------------------------------- "  >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log 
echo "\n Detected Generator: $2 "               >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log 
echo " Detected Project Name: $3 "              >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log 


# If we're using elas_gen 
if ($GEN == "elast_gen") then 
#    cp e1f*.inp e1f.inp
    echo " Running elast_gen " >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    elast_gen < e1f.inp        >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    mv elast_gen.evt gen.bos   >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    mv elast_gen.rz gen.rz     >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    echo " ------------ EVENT GEN DONE ----------- " >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    ls -lh >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log 
    gsim_bat -ffread ffread.in -mcin gen.bos -trig 49999 -kine 1 -bosout GSIMout.bos >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
endif

# If we're using elas_gen 
if ($GEN == "elast_gen_cole") then 
#    cp e1f*.inp e1f.inp
    echo " Running elast_gen " >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    elast_gen_cole < e1f.inp        >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    mv elast_gen.evt gen.bos   >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    mv elast_gen.rz gen.rz     >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    echo " ------------ EVENT GEN DONE ----------- " >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    ls -lh >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log 
    gsim_bat -ffread ffread.in -mcin gen.bos -trig 49999 -kine 1 -bosout GSIMout.bos >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
endif

# If we're using keppel_rad 
if ($GEN == "keppel_rad") then 
    cp *.inp e1f.inp
    keppel_rad < e1f.inp
    mv keppel_rad.evt gen.bos >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    mv keppel_rad.rz gen.rz 
    echo " ------------ EVENT GEN DONE ----------- " >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    ls -lh >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log 
#    h2root genEvents.root keppel_rad.rz 
    gsim_bat -ffread ffread.in -mcin gen.bos -trig 49999 -kine 1 -bosout GSIMout.bos >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
endif

# If we're using keppel_rad with lund file format 
if ($GEN == "keppel_rad_lund") then 
    cp e1*.inp e1f.inp
    keppel_rad < e1f.inp
    mv keppel_rad.evt gen.bos >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    echo " ------------ EVENT GEN DONE ----------- " >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    ls -lh >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log 
    gsim_bat -ffread ffread.in -lund radEvents.gen -trig 50000 -kine 5 -bosout GSIMout.bos >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
endif

# If we're using keppel_norad 
if ($GEN == "keppel_norad") then 
    cp e1*.inp e1f.inp
    keppel_norad < e1f.inp
    mv keppel_norad.evt gen.bos >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    mv fort.88 events.dat  >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    mv keppel_norad.rz gen.rz
    echo " ------------ EVENT GEN DONE ----------- " >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    ls -lh >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log 
#    gsim_bat -ffread ffread.in -lund events.dat -trig 30000 -kine 5 -bosout GSIMout.bos >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    gsim_bat -ffread ffread.in -mcin gen.bos -trig 49999 -kine 1 -bosout GSIMout.bos >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
endif

# If we're using dis_gen 
if ($GEN == "dis_gen" || $GEN == "clasdis") then 
    cp -r ~/mydoc/CLASSourceCode/clasdis/pdf . 
    dis_gen --trig 10000 --datf --outform 2 --beam 5498 --zpos -250 --zwidth 25 --t 5 60 --parl3 0.7 --lst15 145 --path ./TEST_ --parj33 0.3 >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log     
    echo " ------------ EVENT GEN DONE ----------- " >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    ls -lh >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log 
    set GEN_OUT = `ls *.dat` 
    mv $GEN_OUT gen.dat >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
    ls -lh >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log 
    gsim_bat -ffread ffread.in -lund gen.dat -trig 20000 -kine 5 -bosout GSIMout.bos >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
endif

# From here down it doesn't matter what gen you used. 
echo " ------------ GSIM DONE ----------------"  >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
countbos GSIMout.bos                             >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log

# my values 
#gpp_2008 -P0x1b -a1.3819 -b1.3819 -c1.3819 -f0.75 -Y -R37662 -oGPPout.bos GSIMout.bos >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log 
gpp -P0x1b -a1.3819 -b1.3819 -c1.3819 -f0.75 -Y -R37662 -oGPPout.bos GSIMout.bos >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log 

# nathans values 
#gpp_2008 -P0x1b -a2.5 -b2.5 -c2.5 -f0.85 -Y -R37662 -oGPPout.bos GSIMout.bos >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log 
mv GPPout.bos Input 
countbos Input                                                                       >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
echo " ------------ DOCA SMEARING DONE --------- "                                    >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log

# Mauri's scripts for user_ana 
# source /site/12gev_phys/production.csh 1.3

source /u/home/dmriser/cook/mc_tools/v2/cookEnvironment
#user_ana -t recsis_mauri.tcl                                                         >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
#user_ana -t recsis_e1f_MC.tcl                                                         >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
kjuser_ana -t recsis_e1f_MC_old.tcl                                                         >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
nt22maker --mc 2                                                                      >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log

echo " ----------- RECONSTRUCTION DONE ------------ "                                 >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log

# to get h2root 
source /group/clas12/environment.csh 
h2root dstfile.hbook out.root                                                        >> $OUTDIR/$PROJ/JOB_$JOBNUMBER/mc.log
h2root gen.rz gen.root

# send output to folder 
#cp out.root $OUTDIR/$PROJ/JOB_$JOBNUMBER/$JOBNUMBER.root
#cp gen.root $OUTDIR/$PROJ/JOB_$JOBNUMBER/
#cp e1f.inp  $OUTDIR/$PROJ/JOB_$JOBNUMBER/e1f.inp
#cp *.gen    $OUTDIR/$PROJ/JOB_$JOBNUMBER/events.lund
#cp *.dat  $OUTDIR/$PROJ/JOB_$JOBNUMBER/
#cp *.bos    $OUTDIR/$PROJ/JOB_$JOBNUMBER/
#cp *.hbook  $OUTDIR/$PROJ/JOB_$JOBNUMBER/
#cp * $OUTDIR/$PROJ/JOB_$JOBNUMBER/
#cp outfile1 $OUTDIR/$PROJ/JOB_$JOBNUMBER/

cp * $OUTDIR/$PROJ/JOB_$JOBNUMBER/
