# Compile libraries for analysis classes. 

import os, glob 

# Compile the C++ Code 
env = Environment(ENV = {'PATH':os.environ['PATH']})
env.ParseConfig("root-config --glibs --cflags")
env.Append(CCFLAGS = ['-g','-lgfortran'])
env.Append(CPPPATH = ['../'], LIBPATH = ['../'],LIBS = ['FortranModel'])

sources  = glob.glob('*.cc')
env.SharedLibrary('CppModel',sources)
